<?php

function _it_utils_debug_print($obj) {
	print '<pre>';
	print_r($obj);
	print '</pre>';
}

function it_utils_menu() {
	$items = array();

	$items['admin/structure/it_utils'] = array(
		'title' => t('it_utils'),
		'description' => t('Imbibe Tech Utils for Drupal'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
				'it_utils_admin_structure_form',
			NULL),
		'access arguments' => array('administer modules'),
		'file' => 'it_utils.admin.inc',
	);

	return $items;
}
