<?php
// 
// Imbibe Technologies Pvt Ltd® - http://imbibe.in
// Copyright (c) 2014
// by Imbibe Technologies Pvt Ltd
// 
// This software and associated files including documentation (the "Software") is goverened by Microsoft Public License (MS-PL),
// a copy of which is included with the Software as a text file, License.txt.

function _it_utils_debug_print($obj) {
	print '<pre>';
	print_r($obj);
	print '</pre>';
}

function it_utils_menu() {
	$items = array();

	$items['admin/structure/it_utils'] = array(
		'title' => t('IT Utils'),
		'description' => t('Imbibe Tech Utils for Drupal'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
				'it_utils_admin_structure_form',
			NULL),
		'access arguments' => array('administer modules'),
		'file' => 'it_utils.admin.inc',
	);

	return $items;
}
